### ISSUE TITLE
Update smolscale version

### ISSUE THREAD

**Issue by nullchinchilla** [asynchronics/tachyobench#1]
I am the author of `smolscale`; the latest version of `smolscale` uses your excellent `st3` crate and is more than 50% faster. You might want to update your `Cargo.lock` :)

Though, it's still a lot slower than Tokio on message-passing benchmarks like `tachyobench`... I wonder what's the magic trick to Tokio and asynchronix. Is the non-stealable LIFO slot so important? Shouldn't `st3` produce similar results to having a non-stealable LIFO slot, especially since stealing is heavily throttled in smolscale?

**Comment by sbarral** [comment]
Hi!

Done, and thank you for the feedback :-)

I am glad you are working further on `smolscale` and continue to explore other avenues. I admit I have capitulated myself: I did start with `smol` because it was easy to understand and customize, but could never get close to `tokio` in terms of performance due to the cost of re-injecting tasks on the global queue. I did try a few other things but progressively converged towards a design very similar to `tokio`, except for the injection queue. But in the end, the main reason why `asynchronix` is faster than `tokio` is mainly due to a small (but as it turned out quite impactful) innovation in the task system which saves one precious atomic RMW for each scheduled task. Otherwise, the task system is also pretty similar to `async-task` and `tokio`.

I had the exact same expectations as you: I though the LIFO slot would not make a difference if the local queue is LIFO, and was very surprised when I found out it did. In retrospect, the reason appears simple: it is not so much because it is LIFO, but because stores and loads to/from the LIFO slot do not require any synchronization (no atomics).

Also (and this is where I show my poor marketing skills), you may try to swap `st3` for a FIFO queue and see if it makes a difference. This was another counter-intuitive discovery for me: in my main use-case (which is very close to the "pinball" benchmark) it turned out that a local `tokio`-like FIFO queue would actually work a little bit better. The reason still partially eludes me, but I suspect it is related to the fact that it gives each of the channels more time to receive items before their receiver task is polled, so in the end results in less notifications (TBC).

Sorry for the wall of text, maybe I should write some posts about my journey developing `asynchronix` :-)
And by the way, I would be also very interested if you happened to make a write-up about the ideas behind `smolscale`, in particular regarding the load-balancing strategy.

**Comment by nullchinchilla** [comment]
Thanks for your response! 

Despite the name, `smolscale` is not designed similarly to `smol` other than using `async-task`: tasks are injected into the local queue rather than always into the global queue. `smol`/`async-std` *always* schedules tasks onto the global queue, and only later do local queues steal from the global queue and each other --- a massive performance problem, on top of using MPMC queues for all the queues.

 Were you having trouble catching up to `tokio` even when this major `smol` bottleneck is fixed?

`smolscale` used to use `crossbeam-deque`, and it was significantly slower than `st3`. 

As for `smolscale`'s design strategy, it's really motivated by `sosistab`, a UDP-based protocol for bad / censored networks that I wrote for my VPN Geph (think QUIC except with obfuscation, multipath routing, and forward error correction).

`sosistab` is designed in an *extremely* "actory" way: every UDP packet coming in (or message that needs to be sent out) gets passed between at least 5-6 tasks, doing tasks like decryption, batching, statistics gathering, Reed-Solomon reconstruction, etc. Originally, I used `smol`, but an issue I observed is that if these tasks get put on different OS threads, then all this message passing has a huge amount of context-switching overhead. In fact, this can get so bad that using 1 thread is faster than using 16, especially on NUMA systems.

`smolscale` is basically an attempt to make an executor that keeps each "train" of message-passing awakenings on the same OS thread, while avoiding too bad unfairness overall. The basic idea is that while traditional work-stealing steals work whenever threads are idle, we only want to steal work when *some thread is fully loaded*. Otherwise, work-stealing only adds synchronization and context-switching overhead.

I eventually settled on a design like:
- work-stealing queues with a global injector
- tasks are always pushed to the local queue if possible
- when we see new tasks, we *do not* do sibling notification. Otherwise, some other CPU might steal away part of the "train" and cause later context switches to be expensive
- a "monitor" thread signals a random sleeping thread to steal every few milliseconds. This eventually keeps things relatively spread out, though it's still an imperfect solution.

`smolscale` increased `sosistab` throughput by more than 80% over `smol` (probably even more now that it uses `st3`), which is impressive since `sosistab` is a pretty complicated protocol doing heavy things like FEC and encryption. (Maybe it just means that I really hit a pathological case of `smol`).

I'm not sure how `smolscale` compares with `tokio` for `sosistab` honestly, since I never used `tokio` with `sosistab`, and there doesn't seem to be an easy way to run `async-task` tasks on tokio?

(The other part of `smolscale` is the pseudo-preemption, which is basically just expanding the thread pool when I detect that workers aren't making progress. But I may remove that feature --- the current implementation involves atomic increments on *every task pool and worker tick*, which might be slow. And hogging the executor in an async task is a terrible anti-pattern anyway)

**Comment by nullchinchilla** [comment]
In fact, once I removed the atomic increments and decrements on every tick, performance on this benchmark drastically increases (to about half rather than 1/5 the speed of tokio) :)

**Comment by sbarral** [comment]
Well, that's super interesting! I admit I bumped into `smolscale` quite late, when my executor was already more or less in shape, so I am indeed quite ignorant of its inner workings.

Catching up with `tokio` wasn't too hard once I had `st3` ready, plus Carl Lerche had some nice write-ups that explain most of the design decisions. There are also quite a few resources on the go scheduler, which is similar. The fact that `async-task` existed was another very big help at the beginning and I found that it worked just as well as `tokio`'s task system (which AFAIU is based on `async-task`, but even then I am afraid you will not be able to use `async-task` with `tokio`). I did not use any of `tokio`'s code base though, because it is extremely monolithic and (at least for me) quite difficult to fully internalize. In the end, I think the most difficult was to let go of my initial preconceived ideas and accept that many of `tokio`'s design decision (like the LIFO slot) were simply better than mine ;-)

I just read about `sosistab` and admit that this is way over my head (not a network person) but it does seem like our use-cases do have similarities. `asynchronix` is also, at its core, an actor system, and the problem you mention (bad perf. when the executor is not fully loaded) is also a big concern. The monitoring thread idea is very interesting to me. I mitigated this problem by borrowing `tokio`'s and go's idea to have only one worker looking for tasks at a time. Currently I also let a newly unparked thread spin for 1us before giving up looking for tasks, which does help but I wished there was a more elegant solution. I think I will experiment with the monitoring thread idea when I get some time. I am just wondering how much the optimal granularity (I mean the 1ms interval) is problem-dependent.

Re: the cost of atomic increments/decrements, if I remember correctly `tokio` use a total of 4 atomic RMWs to schedule and execute a task on the happy path (and `asynchronix` 1 less), so even 1 RMW can indeed make a pretty big difference.

**Comment by nullchinchilla** [comment]
If you `cargo update` again, smolscale now is almost neck-to-neck with `tokio` for the `funnel` benchmark (I removed the additional RMWs I added unless the `preempt` feature is on, and added a tokio-style LIFO slot):

```
Running benchmark 'funnel' with the smolscale runtime.
    async_channel:
        capacity=1                 11.172 msg/µs
        capacity=10                88.480 msg/µs
        capacity=100              146.743 msg/µs
        capacity=1000             153.593 msg/µs
        capacity=10000            145.318 msg/µs
```

vs

```
Running benchmark 'funnel' with the tokio runtime.
    async_channel:
        capacity=1                 12.493 msg/µs
        capacity=10                71.188 msg/µs
        capacity=100              173.436 msg/µs
        capacity=1000             202.244 msg/µs
        capacity=10000            202.531 msg/µs
```

but on the `pinball` benchmark, `smolscale` doesn't exhibit the huge increase in throughput as "ball count" increases that every other executor exhibits:

```
Running benchmark 'pinball' with the smolscale runtime.
    async_channel:
        ball count=1               46.961 msg/µs
        ball count=3               28.407 msg/µs
        ball count=7               28.549 msg/µs
        ball count=17              30.576 msg/µs
        ball count=41              32.725 msg/µs
        ball count=101             39.655 msg/µs
        ball count=241             46.503 msg/µs
```

vs 
```
Running benchmark 'pinball' with the tokio runtime.
    async_channel:
        ball count=1               51.310 msg/µs
        ball count=3               38.746 msg/µs
        ball count=7               46.456 msg/µs
        ball count=17              51.754 msg/µs
        ball count=41              80.157 msg/µs
        ball count=101            126.820 msg/µs
        ball count=241            149.885 msg/µs
```

This seems to be the case even if I do add in sibling notification. What might this be from? LIFO vs FIFO?

**Comment by sbarral** [comment]
So this looks very good, but indeed the pinball results are a bit puzzling. It's a bit too late now, but I could try to swap the FIFO queue back to `st3` in `asynchronix` tomorrow and see if the behaviour is similar, though from what I recall the differences between FIFO and LIFO were much smaller. That being said I was initially mostly testing on my laptop (2/4 cores only) before I had an EC2 setup, and your test seem to run on a very high core count (8 or 16 cores?).

**Comment by sbarral** [comment]
I was curious so I checked on my laptop and got the same kind of qualitative differences using the latest `smolscale` (which indeed was neck-to-neck with `tokio` on the funnel bench).

I swapped the FIFO queue for `st3` in `asynchronix` and, even though the differences were less drastic, it does look like it may explain what you observe with `smolscale`.

With the default FIFO queue:

```
Running benchmark 'funnel' with the asynchronix runtime.
    async_channel:
        capacity=1                  3.455 msg/µs
        capacity=10                16.043 msg/µs
        capacity=100               27.417 msg/µs
        capacity=1000              29.541 msg/µs
        capacity=10000             29.399 msg/µs

Running benchmark 'pinball' with the asynchronix runtime.
    async_channel:
        ball count=1                8.651 msg/µs
        ball count=3                8.582 msg/µs
        ball count=7                9.642 msg/µs
        ball count=17              12.080 msg/µs
        ball count=41              16.247 msg/µs
        ball count=101             20.583 msg/µs
        ball count=241             23.572 msg/µs
```

With `st3` (LIFO):

```
unning benchmark 'funnel' with the asynchronix runtime.
    async_channel:
        capacity=1                  4.800 msg/µs
        capacity=10                18.521 msg/µs
        capacity=100               27.093 msg/µs
        capacity=1000              28.889 msg/µs
        capacity=10000             27.817 msg/µs

Running benchmark 'pinball' with the asynchronix runtime.
    async_channel:
        ball count=1                8.589 msg/µs
        ball count=3                8.422 msg/µs
        ball count=7                9.198 msg/µs
        ball count=17              10.048 msg/µs
        ball count=41              11.197 msg/µs
        ball count=101             12.500 msg/µs
        ball count=241             14.105 msg/µs
```

Now the good news is that my FIFO queue in `asynchronix` is almost API compatible with `st3`, so you can just copy-paste it to try. If you are interested I may even release it as a separate crate.

**Comment by nullchinchilla** [comment]
Yeah, I am certainly interested in it as a separate crate, or maybe even as an alternative option in `st3`? Right now the only real choices for workstealing queues are `st3` and `crossbeam-deque` (or abusing `concurrent-queue` or `crossbeam-queue`'s bounded MPMC queues, which is often worse than even `crossbeam-deque`); there's no highly optimized bounded work-stealing FIFO queue around

**Comment by sbarral** [comment]
Please have a look at this PR:

https://github.com/asynchronics/st3/pull/1

You can now try the FIFO queue by pointing your `Cargo.toml` to the github repo with the `fifo-lifo` branch.
I'd be very grateful for any feedback regarding the unresolved questions mentioned in the PR description (please respond on the PR; I will close this issue for now but we can still use it for discussions not strictly related to the PR).
